version: '3'
services:
    starwarsapi:
        image: 'star-wars-api'
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
        - '4000:4000'
        environment:
        - NODE_ENV=development
        - PORT=4000
        - DATABASE_URL=postgres://postgres:*Admin12#@localhost:5432/star_wars_db